# Generated by Django 3.0.8 on 2020-08-03 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20200802_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='pic',
            field=models.ImageField(upload_to='%Y/%m/%d'),
        ),
    ]
