# Generated by Django 3.0.8 on 2020-08-09 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0004_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(to='gallery.Item'),
        ),
        migrations.AddField(
            model_name='cart',
            name='totalprice',
            field=models.IntegerField(default=0),
        ),
    ]
