# Generated by Django 3.0.8 on 2020-08-17 18:32

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_auto_20200817_1408'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None),
        ),
    ]
