# Generated by Django 3.0.8 on 2020-08-09 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_auto_20200808_1633'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
